import 'package:get/get.dart';
import 'package:belajarfluuter/models/produk_model.dart';

class ListProdukController extends GetxController {
  List<ProdukModel> listProduk = [
    ProdukModel(
      namaProduk: "5X Ceramide Barrier Repair Moisturizer Gel 30g",
      harga: "Rp 129.000",
      deskripsi:"Moisturizer gel dengan 5X Ceramide untuk memperkuat skin barrier, menjaga kelembapan, dan menenangkan kulit sensitif. Tekstur ringan, cepat meresap.",
      image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQXFShTJU1TzBezsBhrjflX8i4O_dGey1nLS2uS8Tg-ng&s=10",
      reviews:"Rina: Ringan banget, kulit jadi lembap seharian.Cocok buat kulit sensitifku.",
      rating: "4.8",
      namaToko: "Skintific Official Store",
    ),
    ProdukModel(
      namaProduk: "Mugwort Acne Clay Mask Stick 40g",
      harga: "Rp 99.000",
      deskripsi:"Clay mask bentuk stick dengan ekstrak mugwort untuk membersihkan pori, menyerap minyak berlebih, dan membantu mengurangi jerawat.",
      image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRG86AUJASmd_OqKeX3MBNrDQhadnwToCEzlH_XGBbOrQ&s=10",
      reviews:"Sinta: Praktis dipakai, pori terasa lebih bersih. ",
      rating: "4.7",
      namaToko: "Skintific Official Store",
    ),
    ProdukModel(
      namaProduk: "5X Ceramide Low pH Cleanser 80ml",
      harga: "Rp 89.000",
      deskripsi:"Pembersih wajah dengan pH rendah yang lembut, membersihkan tanpa membuat kulit terasa kering atau ketarik.",
      image:"https://images.soco.id/b1bc85a0-277c-4dac-82bd-b4f24d0c9dec-image-0-1765349260072",
      reviews:"Lia: Busanya lembut, nggak bikin kering.",
      rating: "4.6",
      namaToko: "Skintific Official Store",
    ),
    ProdukModel(
      namaProduk: "2% Salicylic Acid Anti Acne Serum 20ml",
      harga: "Rp 109.000",
      deskripsi:"Serum dengan salicylic acid untuk membantu mengurangi jerawat, membersihkan pori, dan menghaluskan tekstur kulit.",
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRstBk5r-RERJnSvc8hjJZUYJsjqI0uUP_wcwxYenWmSA&s",
      reviews:"Nadia: Jerawat kempes dalam beberapa hari.",
      rating: "4.5",
      namaToko: "Skintific Official Store",
    ),
    ProdukModel(
      namaProduk: "10% Niacinamide Brightening Serum 20ml",
      harga: "Rp 119.000",
      deskripsi:"Serum niacinamide untuk mencerahkan, menyamarkan noda, dan mengontrol minyak.",
      image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTErtHPIhcQDY4_1pqiMEDVOzaeGSSWcouk2H73Gs0zrQ&s=10",
      reviews:"Ayu: Wajah lebih cerah dan glowing.",
      rating: "4.7",
      namaToko: "Skintific Official Store",
    ),
    ProdukModel(
      namaProduk: "Symwhite 377 Dark Spot Serum 20ml",
      harga: "Rp 149.000",
      deskripsi:"Serum dengan Symwhite 377 untuk membantu memudarkan flek hitam dan bekas jerawat.",
      image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ40qrS73HUPOck47cYB6d-V67YJiN3PItfcXLd5N1boQ&s=10",
      reviews:"Citra: Bekas jerawat mulai pudar.",
      rating: "4.6",
      namaToko: "Skintific Official Store",
    ),
    ProdukModel(
      namaProduk: "5X Ceramide Barrier Repair Serum 20ml",
      harga: "Rp 135.000",
      deskripsi:"Serum dengan 5X Ceramide yang membantu memperbaiki skin barrier dan mengunci kelembapan kulit.",
      image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR0DlU7YiSknEZJ4gC5w46Nx_4AqPVJgzSRaJY6UV34Nw&s=10",
      reviews:"Bella: Kulit kemerahan jadi lebih tenang.",
      rating: "4.8",
      namaToko: "Skintific Official Store",
    ),
    ProdukModel(
      namaProduk: "All Day Light Sunscreen SPF 35 PA+++ 30ml",
      harga: "Rp 99.000",
      deskripsi:"Sunscreen ringan dengan perlindungan SPF 35 PA+++, nyaman dipakai sehari-hari dan tidak meninggalkan white cast tebal.",
      image:"https://medias.watsons.co.id/publishing/WTCID-39275-side-zoom.jpg?version=1728589282",
      reviews:"Erna: Nggak bikin kusam, oke banget.",
      rating: "4.4",
      namaToko: "Skintific Official Store",
    ),
    ProdukModel(
      namaProduk: "Cover All Perfect Cushion SPF 35 PA+++ 11g",
      harga: "Rp 159.000",
      deskripsi:"Cushion dengan coverage tinggi namun ringan, hasil akhir natural dan tahan lama sepanjang hari.",
      image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQKGEj3vr0WTIps_DZT31MT4zINoTq9Nx2XcZoeCn5fYw&s=10",
      reviews:"Salsa: Coverage-nya bagus, nggak cakey.",
      rating: "4.5",
      namaToko: "Skintific Official Store",
    ),
    ProdukModel(
      namaProduk: "Retinol Face Cream 30g",
      harga: "Rp 139.000",
      deskripsi:"Krim wajah dengan retinol untuk membantu menyamarkan garis halus dan meningkatkan kekenyalan kulit. Gunakan malam hari.",
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQIGFxJBO8dvbB13SZxq9qg3revqR95s7MfL_ma1UT8-w&s",
      reviews:"Gita: Kulit terasa lebih kenyal. ",
      rating: "4.3",
      namaToko: "Skintific Official Store",
    ),
  ];
}